version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: pingador_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  monitor:
    build: ./monitor
    container_name: pingador_monitor
    depends_on:
      pingador_db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

volumes:
  timescale_data:
