
INSERT INTO DEVICES (IP_ADDRESS, HOSTNAME, SITE, TYPE, MONITORING_INTERVAL_SECONDS, PING_TIMEOUT_MILLISECONDS, PING_COUNT, MONITORING_ENABLED, CURRENT_STATUS)
VALUES
('8.8.8.8', 'GOOGLE_DNS', 'SP', 'SRV', 30, 1000, 3, 1, 99),
('1.1.1.1', 'CLOUDFLARE_DNS', 'RJ', 'FIREWALL', 30, 1000, 3, 1, 99);
